version: '3.8'

services:
  websocket-api:
    build: .
    expose:
      - 8001
    networks:
      - projects
    command: gunicorn
    container_name: websocket-api

networks:
  projects:
    external: true