version: '3.8'

services:
  websocket-api:
    build: .
    expose:
      - 8001
    networks:
      - projects
    command: gunicorn
    container_name: websocket-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websocket-api.entrypoints=websecure"
      - "traefik.http.routers.websocket-api.rule=Host(`websocket.aguest.me`)"
      - "traefik.http.routers.websocket-api.tls=true"
      - "traefik.http.routers.websocket-api.tls.certresolver=myresolver"

networks:
  projects:
    external: true